### ISSUE TITLE
Platform Not Supported Exception on MacOS 14.5

### ISSUE THREAD

**Issue by lterry2** [AzureAD/microsoft-authentication-library-for-objc#2310]
When calling `AcquireTokenInteractive` on a .Net 8 MAUI App on MacOS 14.5 using Microsoft.Identity.Client V4.64.0, it will not open up the default system browser and will instead throw a "PlatformNotSupportedException" with the error:
```
Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103
```

And the stack trace is as follows:
```
at Microsoft.Identity.Client.Platforms.netcore.NetCorePlatformProxy.StartDefaultOsBrowserAsync(String url, Boolean isBrokerConfigured)
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.<>c__DisplayClass10_0.<InterceptAuthorizationUriAsync>b__0(Uri u)
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.InterceptAuthorizationUriAsync(Uri authorizationUri, Uri redirectUri, Boolean isBrokerConfigured, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.AcquireAuthorizationAsync(Uri authorizationUri, Uri redirectUri, RequestContext requestContext, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
```

I have ensured that the latest version of the .Net SDK is installed from this site: https://dotnet.microsoft.com/en-us/download/dotnet/8.0

The relevant code looks as follows:
```
public async Task<AuthenticationResult> GetInteractiveToken()
{
        AuthenticationResult result;
        var app = BuildApp();

        var accounts = await app.GetAccountsAsync();

        result = await app.AcquireTokenInteractive(scopes).ExecuteAsync();

        return result;
}

private IPublicClientApplication BuildApp()
{
    var app = PublicClientApplicationBuilder.Create("[ApplicationId]")//Note this is actually populated in my app, just obfuscating it for this post.
        .WithDefaultRedirectUri()
        .Build();

    return app;
}
```

**Comment by juan-arias** [comment]
Hi @lterry2, you might want to ask in the MSAL.NET repository instead: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues
